[build]
  command = "npm run build"
  publish = "./build/"
  functions = "/netlify/functions"
[dev]
  command = "npm run start"
  targetPort = 3000
[functions]
  external_node_modules = ["dotenv","express", "mongodb"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"